---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9
    driver:
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012

suites:
  - name: default
    run_list:
      - recipe[dropbox]
    attributes:
  - name: uninstall
    run_list:
      - recipe[dropbox_test::uninstall]
    attributes:
