---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9
    driver:
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.6
  - name: fedora-25

suites:
  - name: default
    run_list:
      - recipe[dropbox]
  - name: remove
    run_list:
      - recipe[dropbox_test::remove]
