---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.9
    driver:
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[dropbox]
    attributes:
